Repository netglue/laminas-messenger, pull requests merged in 2023-04, with the labels that each got.

#176 Renovate/phpunit phpunit 10.x
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  src/Container/TransportFactory.php
  src/TransportFactoryFactory.php
Labels: enhancement, dependencies

#178 Add the final keyword wherever possible
  src/ConfigProvider.php
  src/Container/Command/ConsumeCommandFactory.php
  src/Container/Command/DebugCommandFactory.php
  src/Container/Command/FailedMessagesRetryCommandFactory.php
  src/Container/Command/FailureCommandAbstractFactory.php
  src/Container/DoctrineTransportFactory.php
  src/Container/MessageBusStaticFactory.php
  src/Container/Middleware/BusNameStampMiddlewareStaticFactory.php
  src/Container/Middleware/MessageHandlerMiddlewareStaticFactory.php
  src/Container/Middleware/MessageSenderMiddlewareStaticFactory.php
  src/Container/RetryStrategyContainerFactory.php
  src/Container/TransportFactory.php
  src/DefaultCommandBusConfigProvider.php
  src/DefaultEventBusConfigProvider.php
  src/Exception/BadMethodCall.php
  src/Exception/ConfigurationError.php
  src/Exception/InvalidServiceType.php
  src/Exception/ServiceNotFound.php
  src/Exception/UnknownTransportScheme.php
  src/FailureCommandsConfigProvider.php
  src/HandlerLocator/OneToManyFqcnContainerHandlerLocator.php
  src/HandlerLocator/OneToOneFqcnContainerHandlerLocator.php
  src/MessageBusOptions.php
  src/RetryStrategyContainer.php
  src/TransportFactoryFactory.php
Labels: enhancement, BC Break

#179 Replace references to deprecated AMQP and Redis transport factories
  .github/composer-require-checker.json
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Exception/MissingDependency.php
  src/TransportFactoryFactory.php
  tests/Exception/MissingDependencyTest.php
  tests/TransportFactoryFactoryTest.php
Labels: enhancement, BC Break

#181 Improve type inference and reduce static analysis issues
  composer.json
  composer.lock
  psalm-baseline.xml
  src/ConfigProvider.php
  src/Container/Command/ConsumeCommandFactory.php
  src/Container/Command/DebugCommandFactory.php
  src/Container/Command/FailedMessagesRetryCommandFactory.php
  src/Container/Command/FailureCommandAbstractFactory.php
  src/Container/FailureTransportRetrievalBehaviour.php
  src/Container/MessageBusOptionsRetrievalBehaviour.php
  src/Container/MessageBusStaticFactory.php
  src/Container/Middleware/BusNameStampMiddlewareStaticFactory.php
  src/Container/Middleware/MessageHandlerMiddlewareStaticFactory.php
  src/Container/Middleware/MessageSenderMiddlewareStaticFactory.php
  src/Container/RetryStrategyContainerFactory.php
  src/Container/TransportFactory.php
  src/Container/Util.php
  src/DefaultCommandBusConfigProvider.php
  src/DefaultEventBusConfigProvider.php
  src/FailureCommandsConfigProvider.php
  src/HandlerLocator/OneToManyFqcnContainerHandlerLocator.php
  src/HandlerLocator/OneToOneFqcnContainerHandlerLocator.php
  src/RetryStrategyContainer.php
  src/TransportFactoryFactory.php
  tests/Container/Command/FailureCommandAbstractFactoryTest.php
  tests/Container/MessageBusOptionsRetrievalBehaviourTest.php
  tests/Container/Middleware/BusNameStampMiddlewareStaticFactoryTest.php
  tests/Container/RetryStrategyContainerFactoryTest.php
  tests/Container/TransportFactoryTest.php
  tests/DefaultCommandBusConfigProviderTest.php
  tests/HandlerLocator/OneToManyFqcnContainerHandlerLocatorTest.php
  tests/HandlerLocator/OneToOneFqcnContainerHandlerLocatorTest.php
  tests/LaminasCliIntegrationTest.php
  tests/MessageBusOptionsTest.php
  tests/RetryStrategyContainerTest.php
  tests/ServiceManagerEventBusIntegrationTest.php
  tests/ServiceManagerIntegrationTest.php
  tests/TransportFactoryFactoryTest.php
Labels: enhancement

#182 Deprecate 'Helper' traits
  psalm-baseline.xml
  src/Container/FailureTransportRetrievalBehaviour.php
  src/Container/MessageBusOptionsRetrievalBehaviour.php
  src/Container/StaticFactoryContainerAssertion.php
Labels: enhancement

#184 Remove deprecated Helper Traits
  psalm-baseline.xml
  src/Container/Command/ConsumeCommandFactory.php
  src/Container/Command/FailedMessagesRetryCommandFactory.php
  src/Container/Command/FailureCommandAbstractFactory.php
  src/Container/FailureTransportRetrievalBehaviour.php
  src/Container/MessageBusOptionsRetrievalBehaviour.php
  src/Container/MessageBusStaticFactory.php
  src/Container/Middleware/BusNameStampMiddlewareStaticFactory.php
  src/Container/Middleware/MessageHandlerMiddlewareStaticFactory.php
  src/Container/Middleware/MessageSenderMiddlewareStaticFactory.php
  src/Container/StaticFactoryContainerAssertion.php
  src/Container/TransportFactory.php
  src/Container/Util.php
  tests/Container/MessageBusOptionsRetrievalBehaviourTest.php
  tests/Container/StaticFactoryContainerAssertionTest.php
Labels: enhancement, BC Break

#185 Fix compatibility with Symfony 6 and support multiple failure transports
  .github/composer-require-checker.json
  composer.json
  composer.lock
  docs/example-failure-transports.php
  docs/example-transport-config.php
  psalm-baseline.xml
  src/ConfigProvider.php
  src/Container/Command/ConsumeCommandFactory.php
  src/Container/Command/FailedMessagesRetryCommandFactory.php
  src/Container/Command/FailureCommandAbstractFactory.php
  src/Container/DoctrineTransportFactory.php
  src/Container/FailureReceiversProvider.php
  src/Container/FailureReceiversProviderFactory.php
  src/Container/FailureSendersProvider.php
  src/Container/FailureSendersProviderFactory.php
  src/Container/TransportFactory.php
  src/Container/Util.php
  src/Exception/ServiceNotFound.php
  src/HandlerLocator/OneToOneFqcnContainerHandlerLocator.php
  src/TransportFactoryFactory.php
  tests/Container/Command/FailureCommandAbstractFactoryTest.php
  tests/Container/FailureReceiversProviderFactoryTest.php
  tests/Container/FailureReceiversProviderTest.php
  tests/Container/FailureSendersProviderFactoryTest.php
  tests/Container/FailureSendersProviderTest.php
  tests/InMemoryContainer.php
  tests/ServiceManagerIntegrationTest.php
Labels: enhancement, dependencies, BC Break

#187 Automatically attach a sigterm listener to the message consumer
  src/Container/Command/ConsumeCommandFactory.php
  tests/ServiceManagerIntegrationTest.php
Labels: enhancement, BC Break

#188 Improve type inference and test coverage.
  psalm-baseline.xml
  src/ConfigProvider.php
  src/Container/Command/DebugCommandFactory.php
  src/Container/Middleware/MessageHandlerMiddlewareStaticFactory.php
  src/Container/Middleware/MessageSenderMiddlewareStaticFactory.php
  src/MessageBusOptions.php
  tests/Container/Middleware/MessageHandlerMiddlewareStaticFactoryTest.php
  tests/Container/Middleware/MessageSenderMiddlewareStaticFactoryTest.php
  tests/MessageBusOptionsTest.php
Labels: documentation, enhancement

#189 Remove composer conflicts with previously incompatible libs
  .gitattributes
  .laminas-ci.json
  composer.json
  composer.lock
Labels: enhancement

#193 Add notes on upgrading from 1.x to 2.x to the README
  README.md
Labels: documentation

#195 Remove CodeCov integration
  .github/workflows/continuous-integration.yml
  README.md
Labels: chore
